// Builds compositions/footage.html from edit.json.
// - segments: hard cuts of assets/source.mp4 (data-media-start + data-duration per segment)
// - captions: timed cues rendered as caption clips
// If the source file is missing, a labelled placeholder panel is written instead of the video
// so `npm run check` and `npm run render` still work.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const edit = JSON.parse(readFileSync(join(root, "edit.json"), "utf8"));
const haveSource = existsSync(join(root, edit.source));

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const fmt = (n) => String(Math.round(n * 1000) / 1000);

// Video band: full width, 16:9 letterboxed into the middle of the 9:16 frame.
const bandW = 1080;
const bandH = Math.round((bandW * edit.sourceHeight) / edit.sourceWidth);
const bandTop = Math.round((1920 - bandH) / 2) - 60;

const segments = edit.segments
  .map((s, i) => {
    if (!haveSource) return "";
    return `
        <video id="fg-seg-${i}" class="clip fg-video" src="${edit.source}" playsinline data-has-audio="true"
          data-start="${fmt(s.start)}" data-duration="${fmt(s.duration)}" data-media-start="${fmt(s.mediaStart)}"
          data-track-index="0" data-volume="1"></video>
        <video id="fg-bg-${i}" class="clip fg-bg" src="${edit.source}" playsinline muted
          data-start="${fmt(s.start)}" data-duration="${fmt(s.duration)}" data-media-start="${fmt(s.mediaStart)}"
          data-track-index="5"></video>`;
  })
  .join("\n");

const placeholder = haveSource
  ? ""
  : `
        <section id="fg-placeholder" class="clip" data-start="0" data-duration="${fmt(edit.sceneDuration)}" data-track-index="0">
          <div class="fg-ph-panel">
            <div class="fg-ph-title">SOURCE FOOTAGE</div>
            <div class="fg-ph-note">${esc(edit.placeholderNote)}</div>
          </div>
        </section>`;

const captions = edit.captions
  .map(
    (c, i) => `
        <div id="fg-cap-${i}" class="clip fg-cap" data-start="${fmt(c.start)}" data-duration="${fmt(c.end - c.start)}" data-track-index="2">
          <span class="fg-cap-text">${esc(c.text)}</span>
        </div>`,
  )
  .join("\n");

const capTweens = edit.captions
  .map(
    (c, i) =>
      `          tl.fromTo("#fg-cap-${i} .fg-cap-text", { scale: 1.18, y: 14, opacity: 0 }, { scale: 1, y: 0, opacity: 1, duration: 0.14, ease: "power3.out" }, ${fmt(c.start)});`,
  )
  .join("\n");

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>footage</title>
    <!-- GENERATED by scripts/build-footage.mjs from edit.json. Edit those, not this file. -->
  </head>
  <body>
    <template>
      <style>
        #footage-root {
          position: absolute;
          inset: 0;
          overflow: hidden;
          background: #0b1b26;
          color: #eef7f8;
          font-family: Inter, Outfit, sans-serif;
        }
        .fg-bg {
          position: absolute;
          left: 50%;
          top: 50%;
          width: ${bandW * 2}px;
          height: ${bandH * 2}px;
          margin: -${bandH}px 0 0 -${bandW}px;
          object-fit: cover;
          filter: blur(40px) brightness(0.45) saturate(1.2);
        }
        .fg-video {
          position: absolute;
          left: 0;
          top: ${bandTop}px;
          width: ${bandW}px;
          height: ${bandH}px;
          object-fit: cover;
          border-radius: 28px;
          box-shadow: 0 30px 80px rgba(0, 0, 0, 0.55);
        }
        #fg-placeholder {
          position: absolute;
          left: 0;
          top: ${bandTop}px;
          width: ${bandW}px;
          height: ${bandH}px;
        }
        .fg-ph-panel {
          position: absolute;
          inset: 0;
          border-radius: 28px;
          border: 4px dashed rgba(10, 154, 168, 0.8);
          background: rgba(10, 154, 168, 0.12);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 20px;
          text-align: center;
          padding: 60px;
        }
        .fg-ph-title {
          font-size: 54px;
          font-weight: 900;
          letter-spacing: 0.2em;
          color: #0a9aa8;
        }
        .fg-ph-note {
          font-size: 34px;
          font-weight: 700;
          color: #c7e3e6;
          line-height: 1.3;
        }
        #fg-topline {
          position: absolute;
          left: 72px;
          right: 72px;
          top: 300px;
          font-family: Outfit, Inter, sans-serif;
          font-size: 64px;
          font-weight: 900;
          line-height: 1.05;
          letter-spacing: -0.03em;
          text-align: center;
        }
        #fg-topline span { color: #0a9aa8; }
        #fg-captions {
          position: absolute;
          left: 0;
          right: 0;
          top: ${bandTop + bandH + 90}px;
          height: 260px;
        }
        .fg-cap {
          position: absolute;
          left: 72px;
          right: 72px;
          top: 0;
          display: flex;
          justify-content: center;
          align-items: center;
        }
        .fg-cap-text {
          display: inline-block;
          padding: 22px 44px;
          border-radius: 24px;
          background: rgba(6, 32, 42, 0.92);
          color: #ffffff;
          font-size: 68px;
          font-weight: 900;
          line-height: 1.1;
          letter-spacing: -0.02em;
          text-align: center;
          text-transform: uppercase;
          box-shadow: 0 10px 40px rgba(0, 0, 0, 0.45);
        }
        #fg-progress {
          position: absolute;
          left: 72px;
          right: 72px;
          top: ${bandTop - 36}px;
          height: 8px;
          border-radius: 4px;
          background: rgba(10, 154, 168, 0.25);
        }
        #fg-progress-fill {
          position: absolute;
          inset: 0;
          border-radius: 4px;
          background: #0a9aa8;
          transform-origin: left center;
        }
      </style>

      <div id="footage-root" data-composition-id="footage" data-width="1080" data-height="1920">
${segments}
${placeholder}
        <section id="fg-chrome" class="clip" data-start="0" data-duration="${fmt(edit.sceneDuration)}" data-track-index="1" data-layout-allow-caption-zone>
          <div id="fg-topline">Recruit affiliates <span>in minutes</span>, not weeks</div>
          <div id="fg-progress"><div id="fg-progress-fill"></div></div>
        </section>
        <div id="fg-captions" data-layout-allow-caption-zone>
${captions}
        </div>
      </div>

      <script>
        (function () {
          const tl = gsap.timeline({ paused: true });
          tl.fromTo("#fg-topline", { y: -40, opacity: 0 }, { y: 0, opacity: 1, duration: 0.5, ease: "power3.out" }, 0.1);
          tl.fromTo("#fg-progress-fill", { scaleX: 0 }, { scaleX: 1, duration: ${fmt(edit.sceneDuration)}, ease: "none" }, 0);
${capTweens}
          window.__timelines["footage"] = tl;
        })();
      </script>
    </template>
  </body>
</html>
`;

writeFileSync(join(root, "compositions/footage.html"), html);
console.log(`footage.html written (${haveSource ? edit.segments.length + " video segment(s)" : "PLACEHOLDER, source missing"}, ${edit.captions.length} captions)`);
